export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const CLEAR_FLASH_MESSAGE = 'CLEAR_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_NEW_BLOG = 'ADD_NEW_BLOG';
export const GET_ALL_BLOG = 'GET_ALL_BLOG';
export const SEARCH_USER='SEARCH_USER';
export const LIST_USERS='LIST_USERS';

